### ISSUE TITLE
cumulative in ratedistortionloss.py maybe use a wrong const.

### ISSUE THREAD

**Issue by FengZiGai** [thekoshkina/learned_image_compression#1]
def cumulative(self, mu, sigma, x):
		"""
		Calculates CDF of Normal distribution with parameters mu and sigma at point x
		"""
		half = 0.5
		const = (2 ** -0.5)
		return half * (1 + torch.erf((x - mu) / (const * sigma)))

I think const should be (2 ** 0.5).

**Comment by thekoshkina** [comment]
You're correct. Thank you
